name: Deploy to Production
on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Image tag (git SHA) to deploy"
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      - uses: hashicorp/setup-terraform@v3
      - name: Deploy to production
        working-directory: terraform
        env:
          TF_VAR_environment: production
          TF_VAR_app_image_tag: ${{ github.event.inputs.image_tag }}
        run: |
          terraform init
          terraform apply -auto-approve