name: Terraform Format Check
on:
    pull_request:
        branches:
            - main
        paths:
            - 'terraform/**'  # Only trigger this workflow for changes in the terraform directory
jobs:
    terraform-fmt:
        runs-on: ubuntu-latest
        steps:
        - name: Check out code
          uses: actions/checkout@v2 
        
        - name: Set up Terraform
          uses: hashicorp/setup-terraform@v3
          with:
                terraform_version: 1.7

        - name: Check Terraform formatting
          run: terraform fmt -check -diff -recursive terraform/

        - name: Debug terraform files
          run: |
                echo "Files:"
                ls -R terraform
                echo "------"
                cat terraform/main.tf
    
    validate:
        runs-on: ubuntu-latest
        needs: terraform-fmt
        steps:
        - name: Check out code
          uses: actions/checkout@v2 
        
        - name: Set up Terraform
          uses: hashicorp/setup-terraform@v3
          with:
                terraform_version: 1.7

        - name: terraform init (no backend)
          run: terraform -chdir=terraform init -backend=false
            
        - name: terraform validate
          run: terraform -chdir=terraform/ validate
        