name: Test OIDC Auth

on:
  workflow_dispatch:   # manually trigger the workflow

permissions:
  id-token: write
  contents: read

jobs:
  test-auth:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::162185499985:role/GitHubActions-notely-devops-app-deploy
          aws-region: ap-south-1

      - name: Verify identity
        run: aws sts get-caller-identity